/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.3 and the Signal Processing Toolbox 6.21.
 * Generated on: 28-Aug-2015 21:38:08
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II
 * Numerator Length    : 7
 * Denominator Length  : 7
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * D:\Program Files\MATLAB\R2014a\extern\include\tmwtypes.h 
 */
const int NL = 7;
const real64_T NUM[7] = {
     0.2469739251843,    1.224022377432,    2.747601952955,    3.536845583958,
      2.747601952955,    1.224022377432,   0.2469739251843
};
const int DL = 7;
const real64_T DEN[7] = {
                   1,    2.482385816396,    3.601589757258,    2.920581370184,
      1.596376526139,   0.4612928358592,  0.09243548466971
};
