/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.8 and Signal Processing Toolbox 8.4.
 * Generated on: 23-Apr-2020 19:17:52
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 54
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2020a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
const int BL = 54;
const int16_T B[54] = {
       -4,     19,     25,     39,     59,     85,    118,    158,    205,
      261,    324,    395,    473,    558,    647,    741,    837,    933,
     1028,   1119,   1204,   1282,   1350,   1407,   1451,   1481,   1496,
     1496,   1481,   1451,   1407,   1350,   1282,   1204,   1119,   1028,
      933,    837,    741,    647,    558,    473,    395,    324,    261,
      205,    158,    118,     85,     59,     39,     25,     19,     -4
};
