/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.8 and Signal Processing Toolbox 8.4.
 * Generated on: 20-Apr-2020 11:00:02
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 68
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2020a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int32 filter coefficients.
 */
const int BL = 68;
const int32_T B[68] = {
        -64896,      113309,      217272,      406472,      695372,     1108442,
       1674955,     2426955,     3397982,     4621905,     6131612,     7957545,
      10126137,    12658173,    15567266,    18858334,    22526500,    26555854,
      30918819,    35575869,    40475646,    45555553,    50742760,    55955655,
      61105867,    66100634,    70845225,    75245442,    79211351,    82658918,
      85513683,    87712744,    89206975,    89962665,    89962665,    89206975,
      87712744,    85513683,    82658918,    79211351,    75245442,    70845225,
      66100634,    61105867,    55955655,    50742760,    45555553,    40475646,
      35575869,    30918819,    26555854,    22526500,    18858334,    15567266,
      12658173,    10126137,     7957545,     6131612,     4621905,     3397982,
       2426955,     1674955,     1108442,      695372,      406472,      217272,
        113309,      -64896
};
