/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.3 and the DSP System Toolbox 8.6.
 * Generated on: 09-Jun-2017 04:20:49
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 3
 * Stable              : Yes
 * Linear Phase        : No
 * Arithmetic          : fixed
 * Numerator           : s25,23 -> [-2 2)
 * Denominator         : s25,23 -> [-2 2)
 * Scale Values        : s25,28 -> [-6.250000e-02 6.250000e-02)
 * Input               : s16,15 -> [-1 1)
 * Section Input       : s16,14 -> [-2 2)
 * Section Output      : s16,11 -> [-16 16)
 * Output              : s16,11 -> [-16 16)
 * State               : s16,15 -> [-1 1)
 * Numerator Prod      : s41,38 -> [-4 4)
 * Denominator Prod    : s41,38 -> [-4 4)
 * Numerator Accum     : s40,35 -> [-16 16)
 * Denominator Accum   : s40,35 -> [-16 16)
 * Round Mode          : convergent
 * Overflow Mode       : wrap
 * Cast Before Sum     : true
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2014a\extern\include\tmwtypes.h 
 */
#define MWSPT_NSEC 7
const int NL[MWSPT_NSEC] = { 1,3,1,3,1,3,1 };
const real64_T NUM[MWSPT_NSEC][3] = {
  {
    0.06195758283138,                 0,                 0 
  },
  {
                   1,   -1.999997377396,                 1 
  },
  {
    0.03417980670929,                 0,                 0 
  },
  {
                   1,   -1.999995112419,                 1 
  },
  {
   0.004718437790871,                 0,                 0 
  },
  {
                   1,    -1.99996316433,                 1 
  },
  {
                   1,                 0,                 0 
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1,3,1,3,1 };
const real64_T DEN[MWSPT_NSEC][3] = {
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.999796867371,   0.9997971057892 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.999429106712,   0.9994293451309 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.999196529388,   0.9991966485977 
  },
  {
                   1,                 0,                 0 
  }
};
